### ISSUE TITLE
Scroll in browser (PDF etc) works in a inverted way

### ISSUE THREAD

**Issue by aghasigrigorian** [vuplex/oculus-webview-example#2]
The scroll when making it with click and drag works in an inverted way, Please see attached video
![PandaMR_XD5bf5CquN](https://user-images.githubusercontent.com/26908592/98086794-acece280-1e98-11eb-9312-c75d3803b6b8.png)
On the image attached above, when dragging with **1** working in an inverted way, when dragging on **2** works normally also the standard scrolling also works normally

Below attaching a video as well

[video.zip](https://github.com/vuplex/oculus-webview-example/files/5486494/video.zip)

**Comment by BinaryNate** [comment]
Hi, @aghasigrigorian 👋. Thank you for using 3D WebView! I really appreciate your business. By default, [WebViewPrefab.DragMode](https://developer.vuplex.com/webview/WebViewPrefab#DragMode) is set to [DragToScroll](https://developer.vuplex.com/webview/DragMode#DragToScroll). In that mode, dragging anywhere on the page results in a call  to [IWebView.Scroll()](https://developer.vuplex.com/webview/IWebView#Scroll) for mobile-like scrolling. In order to drag elements within the page, including scrollbars, WebViewPrefab.DragMode must instead be set to [DragWithinPage](https://developer.vuplex.com/webview/DragMode#DragWithinPage). In that mode, dragging the scrollbar works as expected. Also, just a heads-up for next time: for support, please contact me through the [support page](https://support.vuplex.com/contact) or by emailing support@vuplex.com.
