### ISSUE TITLE
huawei vr sdk question

### ISSUE THREAD

**Issue by fingerx** [vuplex/oculus-webview-example#3]
hi, i want to using your plugins.  i want to know is support huawei vr?
please see
[hvrsdk-unity-3.0.0.31.zip](https://github.com/vuplex/oculus-webview-example/files/5506771/hvrsdk-unity-3.0.0.31.zip)

thanks very much.

**Comment by BinaryNate** [comment]
Hi, @fingerx 👋. For general 3D WebView questions or support, please contact me through the [contact page](https://support.vuplex.com/contact) or by emailing me at support@vuplex.com. I saw that you also sent your question to me through the contact page, and I appreciate that. I just responded to your question via email, but I'll include the answer here, too, in case it is helpful to someone:

3D WebView's prefabs ([WebViewPrefab](https://developer.vuplex.com/webview/WebViewPrefab) and [CanvasWebViewPrefab](https://developer.vuplex.com/webview/CanvasWebViewPrefab)) automatically detect input sent through Unity's input event system like described in [this article](https://support.vuplex.com/articles/how-can-i-get-clicking-to-work). I don't yet have an example project specifically for the Huawei VR SDK, but I added a feature request for that, and I tagged you on it so that I will let you know if I create one in the future. For now, here's the approach I recommend:

• Start with a project that has the Huawei VR SDK installed in it.
• Locate a demo scene from the Huawei VR SDK that demonstrates clicking on objects or Canvas UI.
• Locate 3D WebView's SimpleWebViewDemo scene and copy the WebViewPrefab and SceneManager objects from that scene into the demo scene from the Huawei VR SDK. Or if the Huawei demo scene uses a Canvas, copy the CanvasWebViewPrefab and SceneManager objects from 3D WebView's CanvasWebViewDemo scene into the Huawei demo scene.

If the Huawei VR SDK doesn't include an input module compatible with Unity's built-in event system, you can instead use the Huawei SDK's APIs to implement an [IPointerInputDetector](https://developer.vuplex.com/webview/IPointerInputDetector), attach it to [WebViewPrefab.Collider](https://developer.vuplex.com/webview/WebViewPrefab#Collider), and then pass it to [WebViewPrefab.SetPointerInputDetector()](https://developer.vuplex.com/webview/WebViewPrefab#SetPointerInputDetector).
