### ISSUE TITLE
View is invisible on Oculus Quest with URP

### ISSUE THREAD

**Issue by allanpichardo** [vuplex/oculus-webview-example#4]
The web view is completely invisible when the project is run on the Oculus Quest with the Universal Rendering Pipeline. I have checked that the webview.isInitialized() method returns true, however there is still nothing there. This is with the native (non-Gecko) asset. Any suggestions?

**Comment by BinaryNate** [comment]
Hi, Allan 👋. Thank you for using 3D WebView! I really appreciate your business, and I'm sorry for the inconvenience. Just a heads-up: for future support requests, please [use the contact page](https://support.vuplex.com/contact) or email me at support@vuplex.com. I'll go ahead and answer your question here, though.

3D WebView for Android doesn't yet support URP out-of-the-box. Here's how [the product page](https://assetstore.unity.com/packages/tools/gui/3d-webview-for-android-with-gecko-engine-web-browser-158778) describes it:

>  In order to use OES textures, the Android plugin uses GLSL shaders, which don't work correctly with the Universal Render Pipeline.

I plan to prioritize this issue soon and work with Unity to support to figure it out, and I added you to the waitlist so that I will send you an update here when it is resolved. In the meantime, a workaround is to use the attached WebViewPrefabMaterialAdapter.cs script, which replaces a WebViewPrefab's material with a URP-friendly material and continuously transfers the contents of the original web texture to the new texture. 

[WebViewPrefabMaterialAdapter.cs.txt](https://github.com/vuplex/oculus-webview-example/files/5837923/WebViewPrefabMaterialAdapter.cs.txt)

Here's an example of how to use it:

WebViewPrefabMaterialAdapter _adapter;

```
void Start() {
    // Get a reference to the WebViewPrefab
    var prefab = GameObject.Find("WebViewPrefab").GetComponent<WebViewPrefab>();
    _adapter = WebViewPrefabMaterialAdapter.Instantiate(prefab);
}
```

The downside to this workaround is that it's not as efficient as using the original web texture directly.

**Comment by BinaryNate** [comment]
@allanpichardo an update: I just discovered that disabling SRP Batcher in the URP settings allows 3D WebView for Android to render without the workaround I described:

<img width="202" alt="Screen Shot 2021-01-20 at 5 45 09 PM" src="https://user-images.githubusercontent.com/4952192/105250231-60d04680-5b47-11eb-8513-3d4857deb22b.png">

I'll still let you know when I find a solution to allow SRP to be enabled
