### ISSUE TITLE
How to load local Html file in webview with baseURL like https://xyz.com ?

### ISSUE THREAD

**Issue by saurabhpandey9** [vuplex/oculus-webview-example#5]
I am looking for loading the local Html file in webview with baseURL to avoid cross origin error. The same things I have done with android webview but not able to do with vuplex webview package. 
Looking for your kind attention.

Thank you.

one more request if you can update the gecko package as well.

**Comment by binarynate** [comment]
Hi, Saurabh 👋. Thank you for using 3D WebView! I think you also sent me a message with this question through the [Vuplex contact page](https://support.vuplex.com/contact), which is great, because that's the correct place to ask support questions. I only use GitHub for issues related to the example projects themselves, so I'll go ahead and close this issue. In case it helps someone else, though, here's the response that I sent you via email:

> 3D WebView for Android with Gecko Engine uses the Mozilla GeckoView library as its browser engine, and unfortunately GeckoView doesn't provide any APIs to override the base URL for a page loaded. However, I'm tracking a feature request for this, and I added you to its waitlist so that I'll send you an update if that changes in the future. In the meantime, if you need to load a local page over https, you could potentially include a simple web server within the app itself so that you can load the page from a localhost URL.

I also have a feature request to upgrade GeckoView (currently it's on GeckoView 97), and I added you to its waitlist so that I'll send you an update when I upgrade it.

**Comment by saurabhpandey9** [comment]
Hi,

There is one more library listed on your vuplex website
-*https://store.vuplex.com/webview/android
<https://store.vuplex.com/webview/android>* for Android.
Will it work in oculus with the above things which I am looking for because
it uses Native android webview.
It yes please let me know as I didn't get much info regarding this on your
website.

waiting for your reply.

Thanks & Regards,
Saurabh

**Comment by binarynate** [comment]
You're right—the non-Gecko package includes an [AndroidWebView.LoadHtml()](https://developer.vuplex.com/webview/AndroidWebView#LoadHtml) method that takes a baseUrl as a parameter. It does work on Oculus, and [this page](https://support.vuplex.com/articles/android-comparison) describes the differences between the Gecko and non-Gecko packages. If you'd like to try it, please send me a message through the [Vuplex contact page](https://support.vuplex.com/contact), and I'll send you a version to try.
