### ISSUE TITLE
3D WebView is invisible, and warning 'Shader warning in 'Vuplex/Android Viewport Shader': Vuplex/Android Viewport Shader shader is not supported on this GPU (none of subshaders/fallbacks are suitable)'

### ISSUE THREAD

**Issue by ZimWoodpecker** [vuplex/oculus-webview-example#6]
I'm running a 3D webview on Oculus but nothing is showing. There're two warnings:

Shader warning in 'Vuplex/Android Single Pass Stereo Viewport Shader': Vuplex/Android Single Pass Stereo Viewport Shader shader is not supported on this GPU (none of subshaders/fallbacks are suitable)

Shader warning in 'Vuplex/Android Viewport Shader': Vuplex/Android Viewport Shader shader is not supported on this GPU (none of subshaders/fallbacks are suitable)

Any suggestions to fix it?

**Comment by ZimWoodpecker** [comment]
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/12655182/180205079-c12e615c-92be-4d14-bd14-761ff3aa48b8.png">

**Comment by binarynate** [comment]
Hi, @ZimWoodpecker  👋. Thank you for the details, and I'm sorry for my delayed response! I don't check GitHub issues frequently because they're intended only for issues pertaining to the example repos themselves. In the future, for general support, please contact me [through the Vuplex support contact page](https://support.vuplex.com/contact). 

1. Based on your logs, I see that you're using v3.16. First, can you please upgrade to the latest v4.1 release and check if that resolves the issue for you?

2. If #1 doesn't resolve the issue, can you please contact me [through the Vuplex support contact page](https://support.vuplex.com/contact) so that I can request additional logs from you?
